Adding ru translation of the main page
cpeditor/cpeditor.github.io pull request #148
Opened 2021-02-10 21:27 UTC by DanMax03

Made a translation of the main page + buttons in the top of the main page. Maybe it needs to correct layout.

2021-02-11 00:44 UTC, ouuan commented
Currently, the title is used to indicate that the translation is done in the [need translation list](https://cpeditor.org/ru/need-translation-list/). So you'd better leave other titles unchanged until their translations are finished.

2021-02-14 09:02 UTC, ouuan commented
@IZOBRETATEL777 @sadykhzadeh Do you have time to review in the near future?

2021-02-14 09:49 UTC, IZOBRETATEL777 requested changes

2021-02-14 09:49 UTC, IZOBRETATEL777 commented on content/_index.ru.html
> +						<a class="banner_btn" href="https://github.com/cpeditor/cpeditor">Смотреть на GitHub</a>
Лучше не начинать с союза "А" предложение и объединить "Он помогает..." c "А также.." в сложное, либо заменить "А также" на "Также он умеет". Но первый вариант лучше.

2021-02-14 09:49 UTC, IZOBRETATEL777 commented on content/_index.ru.html
> +			<h2>Как это работает</h2>
Опиционально: добавить знак "?", лучше будет смотреться

2021-02-14 09:50 UTC, IZOBRETATEL777 commented
> @IZOBRETATEL777 @sadykhzadeh Do you have time to review in the near future?

Yes
And Привет for new translator :)

2021-02-14 10:51 UTC, DanMax03 commented
> > @IZOBRETATEL777 @sadykhzadeh Do you have time to review in the near future?
> 
> Yes
> And Привет for new translator :)

Привет, получается)

2021-02-14 10:55 UTC, DanMax03 commented on content/_index.ru.html
> +			<h2>Как это работает</h2>
Можно, конечно же. Но как по мне, символ, отличный от кириллицы будет выделяться в такой фразе. Добавил в коммит

2021-02-14 12:30 UTC, sadykhzadeh approved these changes
The translation was done quite well.

Спасибо, @DanMax03 )

2021-02-14 12:38 UTC, ouuan commented on content/_index.ru.html
> +						<a class="banner_btn" href="https://github.com/cpeditor/cpeditor">Смотреть на GitHub</a>
> Лучше не начинать с союза "А" предложение и объединить "Он помогает..." c "А также.." в сложное, либо заменить "А также" на "Также он умеет". Но первый вариант лучше.

Is this resolved?

2021-02-14 13:47 UTC, DanMax03 commented on content/_index.ru.html
> +						<a class="banner_btn" href="https://github.com/cpeditor/cpeditor">Смотреть на GitHub</a>
Yes, it is.

2021-02-14 14:07 UTC, ouuan approved these changes
Thanks for your contribution!

2021-02-14 14:08 UTC, DanMax03 commented
> Thanks for your contribution!

You're welcome)

2021-02-14 14:10 UTC, ouuan commented
@allcontributors add @DanMax03 as a contributor for translation.

2021-02-14 14:12 UTC, ouuan commented
@IZOBRETATEL777 need your approval.

2021-02-14 14:15 UTC, ouuan commented
@DanMax03 Welcome to be a member of CP Editor! Next time it's preferred to push to a new branch (not the default branch with the name "hugo") of this repo (cpeditor/cpeditor.github.io instead of DanMax03/cpeditor.github.io).

2021-02-14 14:23 UTC, DanMax03 commented
> @DanMax03 Welcome to be a member of CP Editor! Next time it's preferred to push to a new branch (not the default branch with the name "hugo") of this repo (cpeditor/cpeditor.github.io instead of DanMax03/cpeditor.github.io).

Okay, I understand :)

2021-02-14 17:01 UTC, IZOBRETATEL777 approved these changes

2021-02-14 17:01 UTC, merged

2021-06-14 01:19 UTC, ouuan commented
@allcontributors add @IZOBRETATEL777 for review.