feat(about): add ru translations
cpeditor/cpeditor.github.io pull request #181
Opened 2021-06-13 15:30 UTC by DanMax03

For ru reviewers:
Возможно стоит заменить "Изучить Особенности" на "Изучить Преимущества", скажите своё мнение.

2021-06-13 15:35 UTC, Sadykhzadeh requested changes

2021-06-13 15:35 UTC, Sadykhzadeh commented on content/about/_index.ru.html
> +CP Editor - легковесящая, основанная на Qt, кроссплатформенная среда разработки.
Frankly to say, I hear "легковесящая" first time) Maybe "легковесная"?

2021-06-13 15:35 UTC, Sadykhzadeh commented on content/about/_index.ru.html
> +<li class="list-group-item list-group-item-success"><a href="../download">Скачать</a> и попробовать её</li>
Maybe it would be better to omit "её".

2021-06-13 18:51 UTC, DanMax03 commented on content/about/_index.ru.html
> +CP Editor - легковесящая, основанная на Qt, кроссплатформенная среда разработки.
Без двух недель после ЕГЭ как я уже забыл русский... Исправлю

2021-06-13 18:59 UTC, DanMax03 commented on content/about/_index.ru.html
> +<li class="list-group-item list-group-item-success"><a href="../download">Скачать</a> и попробовать её</li>
Yes, it sounds better.

2021-06-13 19:02 UTC, Sadykhzadeh approved these changes
Everything is OK, good job!

2021-06-14 01:15 UTC, ouuan commented on content/about/_index.ru.html
> +<p class="lead mt-5">IDE, созданная специально для спортивного программирования</p>
This is not consistent with: https://github.com/cpeditor/cpeditor.github.io/blob/f7371847179bebfbea297da7dfa07a756c11d8f6/config.toml#L77

2021-06-14 06:34 UTC, DanMax03 commented on content/about/_index.ru.html
> +<p class="lead mt-5">IDE, созданная специально для спортивного программирования</p>
Redone.

2021-06-14 06:45 UTC, ouuan approved these changes

2021-06-14 11:10 UTC, Sadykhzadeh approved these changes
Nice.

2021-06-14 11:33 UTC, merged