feat: add wakatime extension
cpeditor/cpeditor.github.io pull request #204
Opened 2021-08-04 08:21 UTC by swift-zym

cpeditor/cpeditor#953

2021-08-04 08:32 UTC, swift-zym commented
@render update

2021-08-05 05:32 UTC, ouuan requested changes
The same for other languages.

2021-08-05 05:32 UTC, ouuan commented on content/docs/preferences/extensions/_index.md
> +It can be empty if you have the global wakatime config file `~/.wakatime.cfg`.
```suggestion
Can be found at [WakaTime Settings](https://wakatime.com/settings/account).

It can be empty if you have the global wakatime config file `~/.wakatime.cfg`.
```

2021-08-05 05:32 UTC, ouuan commented on content/docs/preferences/extensions/_index.md
> +Use [Advanced>Network Proxy](../advanced/\_index.md#network-proxy) to send data to WakaTime.
```suggestion
Use [Network Proxy](../advanced/\_index.md#network-proxy) to send data to WakaTime.
```

2021-08-05 05:32 UTC, ouuan commented on content/docs/setup/_index.md
> +You can install WakaTime by `pip install -I wakatime==13.1.0`.
```suggestion
If you are a Linux/macOS user and your distro provides the WakaTime CLI, it's recommended to use it.

Otherwise, there are two options:

-   The deprecated Python version. You can install it via `pip install wakatime`.
-   The new Go version. You can download it at <https://github.com/wakatime/wakatime-cli/releases>.
```

2021-08-05 12:11 UTC, ouuan commented on content/docs/setup/_index.md
> +
```suggestion

You can use [WakaTime](https://wakatime.com) to track your time usage.

```

2021-08-05 12:21 UTC, ouuan submitted a review, later dismissed

2021-09-19 04:28 UTC, ouuan approved these changes

2021-09-19 04:29 UTC, merged