Translation of the FAQ section
cpeditor/cpeditor.github.io pull request #282
Opened 2022-07-03 10:38 UTC by gerstudent

Add a translation of the FAQ section from English to Russian

2022-07-03 10:52 UTC, ouuan commented on content/docs/faq/_index.ru.md
> +Вероятно, это связано с тем, что ваш антивирус сканирует вашу программу. Возможным решением является [установка выходной директории для исполняемых файлов](../preferences/language/\_index.ru.md#c-exe
```suggestion
Вероятно, это связано с тем, что ваш антивирус сканирует вашу программу. Возможным решением является [установка выходной директории для исполняемых файлов](../preferences/language/\_index.ru.md#c-executable-file-path) (например, вы можете установить его на `D:/cpeditor-executables/${basename}`), и добавить эту директорию (`D:/cpeditor-executables` в примере) в белый список вашего антивируса.
```

2022-07-04 07:48 UTC, Sadykhzadeh requested changes
awesome translation, great job!👍🏼

but some issues should be fixed. thank you for your great effort.

2022-07-04 07:48 UTC, Sadykhzadeh commented on content/docs/faq/_index.ru.md
> +### Я использую CP Editor на Codeforces, но кнопка отправки недоступна для нажатия.
```suggestion
### Я использую CP Editor на Codeforces, но кнопка отправки отключена.
```

literal translation is not as good as we can see. it would be more native to say that button "is disabled", rather than "unavailable for clicking".

2022-07-04 07:48 UTC, Sadykhzadeh commented on content/docs/faq/_index.ru.md
> +Это происходит потому, что CP Editor не может выполнить команду `cf`. Пожалуйста, убедитесь, что команда указана в PATH, или укажите путь к ней в настройках.
```suggestion
CP Editor не может выполнить команду `cf`. Пожалуйста, убедитесь, что команда указана в PATH, или укажите путь к ней в настройках.
```

In English we can say "It's because", since it's short, concise, and doesn't irritate eyes. In Russian, this kind of beginning is annoying. It’s better to say right away that "the problem is in this", that’s it. Without many words. 

Great translation, btw. :3

2022-07-04 07:48 UTC, Sadykhzadeh commented on content/docs/faq/_index.ru.md
> +CF-Tool требует, чтобы вы настроили его перед использованием. Пожалуйста, запустите `cf config` в терминале, чтобы установить имя пользователя и пароль и добавить шаблон.
```suggestion
Настройте CF-Tool перед использованием. Пожалуйста, запустите `cf config` в терминале для установки имя пользователя с паролем, затем добавьте шаблон.
```

2022-07-04 08:50 UTC, gerstudent commented on content/docs/faq/_index.ru.md
> +Это происходит потому, что CP Editor не может выполнить команду `cf`. Пожалуйста, убедитесь, что команда указана в PATH, или укажите путь к ней в настройках.
Yes you are right. it really looks annoying. Thank you for your feedback, I will definitely take this into account in the next translations.

2022-07-05 14:46 UTC, gerstudent reviewed
Thanks for the helpful changes

2022-07-05 15:06 UTC, ouuan commented
You resolved the conversations without applying the suggestions.

2022-07-06 10:47 UTC, Sadykhzadeh requested changes
Only this one should be rechecked and you can merge it. Thank you a lot for your effort!

2022-07-06 10:47 UTC, Sadykhzadeh commented on content/docs/faq/_index.ru.md
> +Вероятно, это связано с тем, что ваш антивирус сканирует вашу программу. Возможным решением является [установка выходной директории для исполняемых файлов](../preferences/language/\_index.ru.md#c-exe
```suggestion
Вероятно, это связано с тем, что ваш антивирус сканирует вашу программу. Возможным решением является [установка output директории для исполняемых файлов](../preferences/language/\_index.ru.md#c-executable-file-path) (например, вы можете установить его на `D:/cpeditor-executables/${basename}`), и добавить эту директорию (`D:/cpeditor-executables` в примере) в белый список вашего антивируса.
```
there is a small risk that user will be confused by `выходная директория` phrase. :')

2022-07-06 11:44 UTC, gerstudent commented on content/docs/faq/_index.ru.md
> +Вероятно, это связано с тем, что ваш антивирус сканирует вашу программу. Возможным решением является [установка выходной директории для исполняемых файлов](../preferences/language/\_index.ru.md#c-exe
I have been thinking for a long time how to translate this sentence correctly. Your version is definitely better than the previous one. Thanks.

2022-07-06 12:10 UTC, gerstudent reviewed
Improving translation

2022-07-06 13:31 UTC, Sadykhzadeh approved these changes
awesome.

2022-07-06 13:56 UTC, coder3101 approved these changes
😊

2022-07-08 18:51 UTC, gerstudent commented
@ouuan, is it possible to merge this pull request?

2022-07-09 00:42 UTC, merged