feat(About, Download): add Chinese translation
cpeditor/cpeditor.github.io pull request #73
Opened 2020-10-04 09:03 UTC by ChungZH

2020-10-04 12:03 UTC, ouuan requested changes

2020-10-04 12:03 UTC, ouuan commented on content/zh/about/_index.html
> +这个 <a href="/">主页</a> 基于 <a href="https://colorlib.com/" target="_blank">Colorlib</a> 模板。
```suggestion
<a href="/">主页</a> 基于 <a href="https://colorlib.com/" target="_blank">Colorlib</a> 模板制作。
```

2020-10-04 12:03 UTC, ouuan commented on content/zh/download/_index.html
> +                    你可能要使用
```suggestion
                    你可能想要使用
```

2020-10-04 12:03 UTC, ouuan commented on content/zh/download/_index.html
> +                <h2>选择你要下载的平台上的版本</h2>
```suggestion
                <h2>选择你使用的平台和想要下载的版本</h2>
```

2020-10-04 12:03 UTC, ouuan commented on content/zh/download/_index.html
> +                <h2 v-else-if="!selectedAsset" class="text-warning">找不到可用文件</h2>
```suggestion
                <h2 v-else-if="!selectedAsset" class="text-warning">找不到可下载的文件</h2>
```

2020-10-04 12:03 UTC, ouuan commented on content/zh/download/_index.html
> +                                        <span v-if="release === latestStableRelease">(最新稳定)</span>
```suggestion
                                        <span v-if="release === latestStableRelease">(最新稳定版)</span>
```

2020-10-04 12:03 UTC, ouuan commented on content/zh/download/_index.html
> +                                        <span v-else-if="release === releases[0]">(最新预览)</span>
```suggestion
                                        <span v-else-if="release === releases[0]">(最新预览版)</span>
```

2020-10-04 12:44 UTC, ouuan approved these changes
LGTM

2020-10-04 13:06 UTC, coder3101 approved these changes

2020-10-04 13:14 UTC, merged

2020-10-04 13:48 UTC, ouuan commented
@ChungZH Next time remember to squash and merge.

2020-10-05 01:06 UTC, ChungZH commented
> @ChungZH Next time remember to squash and merge.

Ahhhhhhhhhhhhhh 💩